### ISSUE TITLE
Release small amount of data for simulation trial

### ISSUE THREAD

**Issue by Rudy112** [xiaoxiaoxh/UniFolding#3]
Great work and thanks for sharing this!

Would you mind releasing a small amount of training/testing data from CLOTH3D for reproducing the inference in the simulation?  SInce the original dataset is too large to download them all.

**Comment by xiaoxiaoxh** [comment]
Hi, the second training stage of our method is a self-supervised training process, thus you can generate traning data on your own with our simulator and CLOTH3D dataset. You can use a small amount of data from the validation set of CLOTH3D (which only has <50 garments) to do this.
