### ISSUE TITLE
How to actually run this code

### ISSUE THREAD

**Issue by Eirikalb** [xiaoxiaoxh/UniFolding#4]
Hi, I think this work is super cool and I am really looking forward to trying this out in the simulator. I have installed rfuniverse and bought the cloth dynamics. So my next step is basically to load the cloths from cloth3D( I have downloaded the validation data) and run the stage 2 with your pre-trained model. I just want to run the code on my own computer to replicate what you have done and hopefully see a two robot arms successfully fold a tshirt in simulation. I see a mention of a makefile and make targets, but I cannot find that makefile anywhere. Have you changed the way you run your targets? @xiaoxiaoxh

**Comment by xiaoxiaoxh** [comment]
Thanks! I realize that I have forgetton to upload the makefile, and it has been added in the repo.
